use uuid::*;

pub enum Characteristic {
    AlertCategoryID,
    AlertCategoryIDBitMask,
    AlertLevel,
    AlertNotificationControlPoint,
    AlertStatus,
    Appearance,
    BatteryLevel,
    BloodPressureFeature,
    BloodPressureMeasurement,
    BodySensorLocation,
    BootKeyboardInputReport,
    BootMouseInputReport,
    CSCFeature,
    CSCMeasurement,
    CurrentTime,
    CyclingPowerControlPoint,
    CyclingPowerFeature,
    CyclingPowerMeasurement,
    CyclingPowerVector,
    DateTime,
    DayDateTime,
    DayOfWeek,
    DeviceName,
    DistanceOffset,
    ExactTime256,
    FirmwareRevisionString,
    GlucoseFeature,
    GlucoseMeasurement,
    GlucoseMeasurementControl,
    HardwareRevisionString,
    HeartRateControlPoint,
    HeartRateMeasurement,
    HIDControlPoint,
    HIDInformation,
    IEEE1107320601RegulatoryCertificationDataList,
    IntermediateCuffPressure,
    IntermediateTemprature,
    LNControlPoint,
    LNFeature,
    LocalTimeInformation,
    LocationAndSpeed,
    ManufacturerNameString,
    MeasurementInterval,
    ModelNumberString,
    Navigation,
    NewAlert,
    PeripheralPrefferedConnectionParameters,
    PeripheralPrivacyFlag,
    PnPID,
    PositionQuality,
    ProtocolMode,
    ReconnectionAddress,
    RecordAccessControlPoint,
    ReferenceTimeInformation,
    Report,
    ReportMap,
    RingerControlPoint,
    RingerSetting,
    RSCFeature,
    RSCMeasurement,
    SCControlPoint,
    ScanIntervalWindow,
    ScanRefresh,
    SensorLocation,
    SerialNumberString,
    ServiceChanged,
    SoftwareRevisionString,
    SupportedNewAlertCategory,
    SupportedUnreadAlertCategory,
    SystemID,
    TemperatureMeasurement,
    TemperatureType,
    TimeAccuracy,
    TimeSource,
    TimeUpdateControlPoint,
    TimeUpdateState,
    TimeWithDistance,
    TimeZone,
    TXPowerLevel,
    UnreadAlertStatus,
    AggregateInput,
    AnalogInput,
    AnalogOutput,
    DigitalInput,
    DigitalOutput,
    ExactTime100,
    NetworkAvailablity,
    ScientificTemperatureInCelsius,
    SecondaryTimeZone,
    String,
    TemperatureInCelsius,
    TemperatureInFahrenheit,
    TimeBroadcast,
    BatteryLevelState,
    BatteryPowerState,
    PulseOximetryContinuousMeasurement,
    PulseOximetrySpotCheckMeasurement,
    RecordAccessControlPointTestVersion,
    Removable,
    ServiceRequired,
    Unknown(UUID),
}

impl Characteristic {
    pub fn to_uuid(&self) -> UUID {
        UUID::Custom(match *self {
            Characteristic::AlertCategoryID,
            Characteristic::AlertCategoryIDBitMask,
            Characteristic::AlertLevel,
            Characteristic::AlertNotificationControlPoint,
            Characteristic::AlertStatus,
            Characteristic::Appearance,
            Characteristic::BatteryLevel,
            Characteristic::BloodPressureFeature,
            Characteristic::BloodPressureMeasurement,
            Characteristic::BodySensorLocation,
            Characteristic::BootKeyboardInputReport,
            Characteristic::BootMouseInputReport,
            Characteristic::CSCFeature,
            Characteristic::CSCMeasurement,
            Characteristic::CurrentTime,
            Characteristic::CyclingPowerControlPoint,
            Characteristic::CyclingPowerFeature,
            Characteristic::CyclingPowerMeasurement,
            Characteristic::CyclingPowerVector,
            Characteristic::DateTime,
            Characteristic::DayDateTime,
            Characteristic::DayOfWeek,
            Characteristic::DeviceName,
            Characteristic::DistanceOffset,
            Characteristic::ExactTime256,
            Characteristic::FirmwareRevisionString,
            Characteristic::GlucoseFeature,
            Characteristic::GlucoseMeasurement,
            Characteristic::GlucoseMeasurementControl,
            Characteristic::HardwareRevisionString,
            Characteristic::HeartRateControlPoint,
            Characteristic::HeartRateMeasurement,
            Characteristic::HIDControlPoint,
            Characteristic::HIDInformation,
            Characteristic::IEEE1107320601RegulatoryCertificationDataList,
            Characteristic::IntermediateCuffPressure,
            Characteristic::IntermediateTemprature,
            Characteristic::LNControlPoint,
            Characteristic::LNFeature,
            Characteristic::LocalTimeInformation,
            Characteristic::LocationAndSpeed,
            Characteristic::ManufacturerNameString,
            Characteristic::MeasurementInterval,
            Characteristic::ModelNumberString,
            Characteristic::Navigation,
            Characteristic::NewAlert,
            Characteristic::PeripheralPrefferedConnectionParameters,
            Characteristic::PeripheralPrivacyFlag,
            Characteristic::PnPID,
            Characteristic::PositionQuality,
            Characteristic::ProtocolMode,
            Characteristic::ReconnectionAddress,
            Characteristic::RecordAccessControlPoint,
            Characteristic::ReferenceTimeInformation,
            Characteristic::Report,
            Characteristic::ReportMap,
            Characteristic::RingerControlPoint,
            Characteristic::RingerSetting,
            Characteristic::RSCFeature,
            Characteristic::RSCMeasurement,
            Characteristic::SCControlPoint,
            Characteristic::ScanIntervalWindow,
            Characteristic::ScanRefresh,
            Characteristic::SensorLocation,
            Characteristic::SerialNumberString,
            Characteristic::ServiceChanged,
            Characteristic::SoftwareRevisionString,
            Characteristic::SupportedNewAlertCategory,
            Characteristic::SupportedUnreadAlertCategory,
            Characteristic::SystemID,
            Characteristic::TemperatureMeasurement,
            Characteristic::TemperatureType,
            Characteristic::TimeAccuracy,
            Characteristic::TimeSource,
            Characteristic::TimeUpdateControlPoint,
            Characteristic::TimeUpdateState,
            Characteristic::TimeWithDistance,
            Characteristic::TimeZone,
            Characteristic::TXPowerLevel,
            Characteristic::UnreadAlertStatus,
            Characteristic::AggregateInput,
            Characteristic::AnalogInput,
            Characteristic::AnalogOutput,
            Characteristic::DigitalInput,
            Characteristic::DigitalOutput,
            Characteristic::ExactTime100,
            Characteristic::NetworkAvailablity,
            Characteristic::ScientificTemperatureInCelsius,
            Characteristic::SecondaryTimeZone,
            Characteristic::String,
            Characteristic::TemperatureInCelsius,
            Characteristic::TemperatureInFahrenheit,
            Characteristic:TimeBroadcast,
            Characteristic::BatteryLevelState,
            Characteristic::BatteryPowerState,
            Characteristic::PulseOximetryContinuousMeasurement,
            Characteristic::PulseOximetrySpotCheckMeasurement,
            Characteristic::RecordAccessControlPointTestVersion,
            Characteristic::Removable,
            Characteristic::ServiceRequired,
            Characteristic::Unknown(ref uuid) => *uuid.to_hex(),
        })
    }

    pub fn from_uuid(uuid: UUID) -> Characteristic {

    }

    pub fn to_str(&self) -> &'static str {
        match *self {
            Characteristic::AlertCategoryID => "Alert Category ID",
            Characteristic::AlertCategoryIDBitMask => "Alert Category ID Bit Mask",
            Characteristic::AlertLevel => "Alert Level",
            Characteristic::AlertNotificationControlPoint => "Alert Notification Control Point",
            Characteristic::AlertStatus => "Alert Status",
            Characteristic::Appearance => "Appearance",
            Characteristic::BatteryLevel => "Battery Level",
            Characteristic::BloodPressureFeature => "Blood Pressure Feature",
            Characteristic::BloodPressureMeasurement => "Blood Pressure Measurement",
            Characteristic::BodySensorLocation => "Body Sensor Location",
            Characteristic::BootKeyboardInputReport => "Boot Keyboard Input Report",
            Characteristic::BootMouseInputReport => "Boot Mouse Input Report",
            Characteristic::CSCFeature => "CSC Feature",
            Characteristic::CSCMeasurement => "CSC Measurement",
            Characteristic::CurrentTime => "Current Time",
            Characteristic::CyclingPowerControlPoint => "Cycling Power Control Point",
            Characteristic::CyclingPowerFeature => "Cycling Power Feature",
            Characteristic::CyclingPowerMeasurement => "Cycling Power Measurement",
            Characteristic::CyclingPowerVector => "Cycling Power Vector",
            Characteristic::DateTime => "Data Time",
            Characteristic::DayDateTime => "Day Date Time",
            Characteristic::DayOfWeek => "Day of Week",
            Characteristic::DeviceName => "Device Name",
            Characteristic::DistanceOffset => "Distance Offset",
            Characteristic::ExactTime256 => "Exact Time 256",
            Characteristic::FirmwareRevisionString => "Fireware Revision String",
            Characteristic::GlucoseFeature => "Glucose Feature",
            Characteristic::GlucoseMeasurement => "Glucose Measurement",
            Characteristic::GlucoseMeasurementControl => "Glucose Measurement Control",
            Characteristic::HardwareRevisionString => "Hardware Revision String",
            Characteristic::HeartRateControlPoint => "Heart Rate Control Point",
            Characteristic::HeartRateMeasurement => "Heart Rate Measurement",
            Characteristic::HIDControlPoint => "HID Control Point",
            Characteristic::HIDInformation => "HID Information",
            Characteristic::IEEE1107320601RegulatoryCertificationDataList => "IEEE 1107320601RegulatoryCertificationDataList",
            Characteristic::IntermediateCuffPressure => "Intermediate Cuff Pressure",
            Characteristic:IntermediateTemprature => "Intermediate Temprature",
            Characteristic::LNControlPoint => "LN Control Point",
            Characteristic::LNFeature => "LN Feature",
            Characteristic::LocalTimeInformation => "Local Time Information",
            Characteristic::LocationAndSpeed => "Location and Speed",
            Characteristic::ManufacturerNameString => "Manufacturer Name String",
            Characteristic::MeasurementInterval => "Measurement Interval",
            Characteristic::ModelNumberString => "Model Number String",
            Characteristic::Navigation => "Navigation",
            Characteristic::NewAlert => "New Alert",
            Characteristic::PeripheralPrefferedConnectionParameters => "Peripheral Preffered Connection Parameters",
            Characteristic::PeripheralPrivacyFlag => "Peripheral Privacy Flag",
            Characteristic::PnPID => "PnP ID",
            Characteristic::PositionQuality => "Position Quality",
            Characteristic::ProtocolMode => "Protocol Mode",
            Characteristic::ReconnectionAddress => "Reconnection Address",
            Characteristic::RecordAccessControlPoint => "Record Access Control Point",
            Characteristic::ReferenceTimeInformation => "Reference Time Information",
            Characteristic::Report => "Report",
            Characteristic::ReportMap => "Report Map",
            Characteristic::RingerControlPoint => "Ringer Control Point",
            Characteristic::RingerSetting => "Ringer Setting",
            Characteristic::RSCFeature => "RSC Feature",
            Characteristic::RSCMeasurement => "RSC Measurement",
            Characteristic::SCControlPoint => "SCC Control Point",
            Characteristic::ScanIntervalWindow => "Scan Interval Window",
            Characteristic::ScanRefresh => "Scan Refresh",
            Characteristic::SensorLocation => "Sensor Location",
            Characteristic::SerialNumberString => "Serial Number String",
            Characteristic::ServiceChanged => "Service Changed",
            Characteristic::SoftwareRevisionString => "Software Revision String",
            Characteristic::SupportedNewAlertCategory => "Supported New Alert Category",
            Characteristic::SupportedUnreadAlertCategory => "Supportd Unread Alert Category",
            Characteristic::SystemID => "System ID",
            Characteristic::TemperatureMeasurement => "Temprature Measurement",
            Characteristic::TemperatureType => "Temprature Type",
            Characteristic::TimeAccuracy => "Time Accuracy",
            Characteristic::TimeSource => "Time Source",
            Characteristic::TimeUpdateControlPoint => "Time Update Control Point",
            Characteristic::TimeUpdateState => "Time Update State",
            Characteristic::TimeWithDistance => "Time wit Distance",
            Characteristic::TimeZone => "Timezone",
            Characteristic::TXPowerLevel => "TX Power Level",
            Characteristic::UnreadAlertStatus => "Unread Alert Status",
            Characteristic::AggregateInput => Aggregate Input,
            Characteristic::AnalogInput => "Analog Input",
            Characteristic::AnalogOutput => "Analog Output",
            Characteristic::DigitalInput => "Digital Input",
            Characteristic::DigitalOutput => "Digital Output",
            Characteristic::ExactTime100 => "Exact Time 100",
            Characteristic::NetworkAvailablity => "Network Availability",
            Characteristic::ScientificTemperatureInCelsius => "Scientific Temperature in Celsius",
            Characteristic::SecondaryTimeZone => "Secondary Time Zone",
            Characteristic::String => "String",
            Characteristic::TemperatureInCelsius => "Temperature in Celsius",
            Characteristic::TemperatureInFahrenheit => "Temperature in Fahrenheit",
            Characteristic::TimeBroadcast => "Time Broadcast",
            Characteristic::BatteryLevelState => "Battery Level State",
            Characteristic::BatteryPowerState => "Battery Power State",
            Characteristic::PulseOximetryContinuousMeasurement => "Pulse Oximetry Continuous Measurement",
            Characteristic::PulseOximetrySpotCheckMeasurement => "Pulse Oximetry Spot Check Measurement",
            Characteristic::RecordAccessControlPointTestVersion => "Record Access Control Point Test Version",
            Characteristic::Removable => "Removable",
            Characteristic::ServiceRequired => "Service Required",
            Characteristic::Unknown => "Unknown",
        }
    }
}
