use uuid::*;

pub enum Characteristic {
    AlertCategoryID,
    AlertCategoryIDBitMask,
    AlertLevel,
    AlertNotificationControlPoint,
    AlertStatus,
    Appearance,
    BatteryLevel,
    BloodPressureFeature,
    BloodPressureMeasurement,
    BodySensorLocation,
    BootKeyboardInputReport,
    BootMouseInputReport,
    CSCFeature,
    CSCMeasurement,
    CurrentTime,
    CyclingPowerControlPoint,
    CyclingPowerFeature,
    CyclingPowerMeasurement,
    CyclingPowerVector,
    DateTime,
    DayDateTime,
    DayOfWeek,
    DeviceName,
    DistanceOffset,
    ExactTime256,
    FirmwareRevisionString,
    GlucoseFeature,
    GlucoseMeasurement,
    GlucoseMeasurementControl,
    HardwareRevisionString,
    HeartRateControlPoint,
    HeartRateMeasurement,
    HIDControlPoint,
    HIDInformation,
    IEEE1107320601RegulatoryCertificationDataList,
    IntermediateCuffPressure,
    IntermediateTemprature,
    LNControlPoint,
    LNFeature,
    LocalTimeInformation,
    LocationAndSpeed,
    ManufacturerNameString,
    MeasurementInterval,
    ModelNumberString,
    Navigation,
    NewAlert,
    PeripheralPrefferedConnectionParameters,
    PeripheralPrivacyFlag,
    PnPID,
    PositionQuality,
    ProtocolMode,
    ReconnectionAddress,
    RecordAccessControlPoint,
    ReferenceTimeInformation,
    Report,
    ReportMap,
    RingerControlPoint,
    RingerSetting,
    RSCFeature,
    RSCMeasurement,
    SCControlPoint,
    ScanIntervalWindow,
    ScanRefresh,
    SensorLocation,
    SerialNumberString,
    ServiceChanged,
    SoftwareRevisionString,
    SupportedNewAlertCategory,
    SupportedUnreadAlertCategory,
    SystemID,
    TemperatureMeasurement,
    TemperatureType,
    TimeAccuracy,
    TimeSource,
    TimeUpdateControlPoint,
    TimeUpdateState,
    TimeWithDistance,
    TimeZone,
    TXPowerLevel,
    UnreadAlertStatus,
    AggregateInput,
    AnalogInput,
    AnalogOutput,
    DigitalInput,
    DigitalOutput,
    ExactTime100,
    NetworkAvailablity,
    ScientificTemperatureInCelsius,
    SecondaryTimeZone,
    String,
    TemperatureInCelsius,
    TemperatureInFahrenheit,
    TimeBroadcast,
    BatteryLevelState,
    BatteryPowerState,
    PulseOximetryContinuousMeasurement,
    PulseOximetrySpotCheckMeasurement,
    RecordAccessControlPointTestVersion,
    Removable,
    ServiceRequired,
    Unknown(UUID),
}

impl Characteristic {
    pub fn to_uuid(&self) -> UUID {
        UUID::Custom(match *self {
            Characteristic::AlertCategoryID => 0x2a43,
            Characteristic::AlertCategoryIDBitMask => 0x2a42,
            Characteristic::AlertLevel => 0x2a06,
            Characteristic::AlertNotificationControlPoint => 0x2a44,
            Characteristic::AlertStatus => 0x2a3f,
            Characteristic::Appearance => 0x2a01,
            Characteristic::BatteryLevel => 0x2a19,
            Characteristic::BloodPressureFeature => 0x2a49,
            Characteristic::BloodPressureMeasurement => 0x2a35,
            Characteristic::BodySensorLocation => 0x2a38,
            Characteristic::BootKeyboardInputReport => 0x2a22,
            Characteristic::BootMouseInputReport => 0x2a33,
            Characteristic::CSCFeature => 0x2a5c,
            Characteristic::CSCMeasurement => 0x2a5b,
            Characteristic::CurrentTime => 0x2a2b,
            Characteristic::CyclingPowerControlPoint => 0x2a66,
            Characteristic::CyclingPowerFeature => 0x2a65,
            Characteristic::CyclingPowerMeasurement => 0x2a63,
            Characteristic::CyclingPowerVector => 0x2a64,
            Characteristic::DateTime => 0x2a08,
            Characteristic::DayDateTime => 0x2a0a,
            Characteristic::DayOfWeek => 0x2a09,
            Characteristic::DeviceName => 0x2a00,
            Characteristic::DistanceOffset => 0x2a0d,
            Characteristic::ExactTime256 => 0x2a0c,
            Characteristic::FirmwareRevisionString => 0x2a26,
            Characteristic::GlucoseFeature => 0x2a51,
            Characteristic::GlucoseMeasurement => 0x2a18,
            Characteristic::GlucoseMeasurementControl => 0x2a34,
            Characteristic::HardwareRevisionString => 0x2a27,
            Characteristic::HeartRateControlPoint => 0x2a39,
            Characteristic::HeartRateMeasurement => 0x2a37,
            Characteristic::HIDControlPoint => 0x2a4c,
            Characteristic::HIDInformation => 0x2a4a,
            Characteristic::IEEE1107320601RegulatoryCertificationDataList => 0x2a2a,
            Characteristic::IntermediateCuffPressure => 0x2a36,
            Characteristic::IntermediateTemprature => 0x2a1e,
            Characteristic::LNControlPoint => 0x2a6b,
            Characteristic::LNFeature => 0x2a6a,
            Characteristic::LocalTimeInformation => 0x2a0f,
            Characteristic::LocationAndSpeed => 0x2a67,
            Characteristic::ManufacturerNameString => 0x2a29,
            Characteristic::MeasurementInterval => 0x2a21,
            Characteristic::ModelNumberString => 0x2a24,
            Characteristic::Navigation => 0x2a68,
            Characteristic::NewAlert => 0x2a46,
            Characteristic::PeripheralPrefferedConnectionParameters => 0x2a04,
            Characteristic::PeripheralPrivacyFlag => 0x2a02,
            Characteristic::PnPID => 0x2a50,
            Characteristic::PositionQuality => 0x2a69,
            Characteristic::ProtocolMode => 0x2a4e,
            Characteristic::ReconnectionAddress => 0x2a03,
            Characteristic::RecordAccessControlPoint => 0x2a52,
            Characteristic::ReferenceTimeInformation => 0x2a14,
            Characteristic::Report => 0x2a4d,
            Characteristic::ReportMap => 0x2a4b,
            Characteristic::RingerControlPoint => 0x2a40,
            Characteristic::RingerSetting => 0x2a41,
            Characteristic::RSCFeature => 0x2a54,
            Characteristic::RSCMeasurement => 0x2a53,
            Characteristic::SCControlPoint => 0x2a55,
            Characteristic::ScanIntervalWindow => 0x2a4f,
            Characteristic::ScanRefresh => 0x2a31,
            Characteristic::SensorLocation => 0x2a5d,
            Characteristic::SerialNumberString => 0x2a25,
            Characteristic::ServiceChanged => 0x2a05,
            Characteristic::SoftwareRevisionString => 0x2a28,
            Characteristic::SupportedNewAlertCategory => 0x2a47,
            Characteristic::SupportedUnreadAlertCategory => 0x2a48,
            Characteristic::SystemID => 0x2a23,
            Characteristic::TemperatureMeasurement => 0x2a1c,
            Characteristic::TemperatureType => 0x2a1d,
            Characteristic::TimeAccuracy => 0x2a12,
            Characteristic::TimeSource => 0x2a13,
            Characteristic::TimeUpdateControlPoint => 0x2a16,
            Characteristic::TimeUpdateState => 0x2a17,
            Characteristic::TimeWithDistance => 0x2a11,
            Characteristic::TimeZone => 0x2a0e,
            Characteristic::TXPowerLevel => 0x2a07,
            Characteristic::UnreadAlertStatus => 0x2a45,
            Characteristic::AggregateInput => 0x2a5a,
            Characteristic::AnalogInput => 0x2a58,
            Characteristic::AnalogOutput => 0x2a59,
            Characteristic::DigitalInput => 0x2a56,
            Characteristic::DigitalOutput => 0x2a57,
            Characteristic::ExactTime100 => 0x2a0b,
            Characteristic::NetworkAvailablity => 0x2a3e,
            Characteristic::ScientificTemperatureInCelsius => 0x2a3c,
            Characteristic::SecondaryTimeZone => 0x2a10,
            Characteristic::String => 0x2a3d,
            Characteristic::TemperatureInCelsius => 0x2a1f,
            Characteristic::TemperatureInFahrenheit => 0x2a20,
            Characteristic:TimeBroadcast => 0x2a15,
            Characteristic::BatteryLevelState => 0x2a1b,
            Characteristic::BatteryPowerState => 0x2a1a,
            Characteristic::PulseOximetryContinuousMeasurement => 0x2a5f,
            Characteristic::PulseOximetrySpotCheckMeasurement => 0x2a62,
            Characteristic::RecordAccessControlPointTestVersion => 0x2a52,
            Characteristic::Removable => 0x2a3a,
            Characteristic::ServiceRequired => 0x2a3b,
            Characteristic::Unknown(ref uuid) => *uuid.to_hex(),
        })
    }

    pub fn from_uuid(uuid: UUID) -> Characteristic {
        match uuid.to_hex() {
            0x2a43 => Characteristic::AlertCategoryID,
            0x2a42 => Characteristic::AlertCategoryIDBitMask,
            0x2a06 => Characteristic::AlertLevel,
            0x2a44 => Characteristic::AlertNotificationControlPoint,
            0x2a3f => Characteristic::AlertStatus,
            0x2a01 => Characteristic::Appearance,
            0x2a19 => Characteristic::BatteryLevel,
            0x2a49 => Characteristic::BloodPressureFeature,
            0x2a35 => Characteristic::BloodPressureMeasurement,
            0x2a38 => Characteristic::BodySensorLocation,
            0x2a22 => Characteristic::BootKeyboardInputReport,
            0x2a33 => Characteristic::BootMouseInputReport,
            0x2a5c => Characteristic::CSCFeature,
            0x2a5b => Characteristic::CSCMeasurement,
            0x2a2b => Characteristic::CurrentTime,
            0x2a66 => Characteristic::CyclingPowerControlPoint,
            0x2a65 => Characteristic::CyclingPowerFeature,
            0x2a63 => Characteristic::CyclingPowerMeasurement,
            0x2a64 => Characteristic::CyclingPowerVector,
            0x2a08 => Characteristic::DateTime,
            0x2a0a => Characteristic::DayDateTime,
            0x2a09 => Characteristic::DayOfWeek,
            0x2a00 => Characteristic::DeviceName,
            0x2a0d => Characteristic::DistanceOffset,
            0x2a0c => Characteristic::ExactTime256,
            0x2a26 => Characteristic::FirmwareRevisionString,
            0x2a51 => Characteristic::GlucoseFeature,
            0x2a18 => Characteristic::GlucoseMeasurement,
            0x2a34 => Characteristic::GlucoseMeasurementControl,
            0x2a27 => Characteristic::HardwareRevisionString,
            0x2a39 => Characteristic::HeartRateControlPoint,
            0x2a37 => Characteristic::HeartRateMeasurement,
            0x2a4c => Characteristic::HIDControlPoint,
            0x2a4a => Characteristic::HIDInformation,
            0x2a2a => Characteristic::IEEE1107320601RegulatoryCertificationDataList,
            0x2a36 => Characteristic::IntermediateCuffPressure,
            0x2a1e => Characteristic::IntermediateTemprature,
            0x2a6b => Characteristic::LNControlPoint,
            0x2a6a => Characteristic::LNFeature,
            0x2a0f => Characteristic::LocalTimeInformation,
            0x2a67 => Characteristic::LocationAndSpeed,
            0x2a29 => Characteristic::ManufacturerNameString,
            0x2a21 => Characteristic::MeasurementInterval,
            0x2a24 => Characteristic::ModelNumberString,
            0x2a68 => Characteristic::Navigation,
            0x2a46 => Characteristic::NewAlert,
            0x2a04 => Characteristic::PeripheralPrefferedConnectionParameters,
            0x2a02 => Characteristic::PeripheralPrivacyFlag,
            0x2a50 => Characteristic::PnPID,
            0x2a69 => Characteristic::PositionQuality,
            0x2a4e => Characteristic::ProtocolMode,
            0x2a03 => Characteristic::ReconnectionAddress,
            0x2a52 => Characteristic::RecordAccessControlPoint,
            0x2a14 => Characteristic::ReferenceTimeInformation,
            0x2a4d => Characteristic::Report,
            0x2a4b => Characteristic::ReportMap,
            0x2a40 => Characteristic::RingerControlPoint,
            0x2a41 => Characteristic::RingerSetting,
            0x2a54 => Characteristic::RSCFeature,
            0x2a53 => Characteristic::RSCMeasurement,
            0x2a55 => Characteristic::SCControlPoint,
            0x2a4f => Characteristic::ScanIntervalWindow,
            0x2a31 => Characteristic::ScanRefresh,
            0x2a5d => Characteristic::SensorLocation,
            0x2a25 => Characteristic::SerialNumberString,
            0x2a05 => Characteristic::ServiceChanged,
            0x2a28 => Characteristic::SoftwareRevisionString,
            0x2a47 => Characteristic::SupportedNewAlertCategory,
            0x2a48 => Characteristic::SupportedUnreadAlertCategory,
            0x2a23 => Characteristic::SystemID,
            0x2a1c => Characteristic::TemperatureMeasurement,
            0x2a1d => Characteristic::TemperatureType,
            0x2a12 => Characteristic::TimeAccuracy,
            0x2a13 => Characteristic::TimeSource,
            0x2a16 => Characteristic::TimeUpdateControlPoint,
            0x2a17 => Characteristic::TimeUpdateState,
            0x2a11 => Characteristic::TimeWithDistance,
            0x2a0e => Characteristic::TimeZone,
            0x2a07 => Characteristic::TXPowerLevel,
            0x2a45 => Characteristic::UnreadAlertStatus,
            0x2a5a => Characteristic::AggregateInput,
            0x2a58 => Characteristic::AnalogInput,
            0x2a59 => Characteristic::AnalogOutput,
            0x2a56 => Characteristic::DigitalInput,
            0x2a57 => Characteristic::DigitalOutput,
            0x2a0b => Characteristic::ExactTime100,
            0x2a3e => Characteristic::NetworkAvailablity,
            0x2a3c => Characteristic::ScientificTemperatureInCelsius,
            0x2a10 => Characteristic::SecondaryTimeZone,
            0x2a3d => Characteristic::String,
            0x2a1f => Characteristic::TemperatureInCelsius,
            0x2a20 => Characteristic::TemperatureInFahrenheit,
            0x2a15 => Characteristic:TimeBroadcast,
            0x2a1b => Characteristic::BatteryLevelState,
            0x2a1a => Characteristic::BatteryPowerState,
            0x2a5f => Characteristic::PulseOximetryContinuousMeasurement,
            0x2a62 => Characteristic::PulseOximetrySpotCheckMeasurement,
            0x2a52 => Characteristic::RecordAccessControlPointTestVersion,
            0x2a3a => Characteristic::Removable,
            0x2a3b => Characteristic::ServiceRequired,
            _ => Characteristic::Unknown(uuid),
        }
    }

    pub fn to_str(&self) -> &'static str {
        match *self {
            Characteristic::AlertCategoryID => "Alert Category ID",
            Characteristic::AlertCategoryIDBitMask => "Alert Category ID Bit Mask",
            Characteristic::AlertLevel => "Alert Level",
            Characteristic::AlertNotificationControlPoint => "Alert Notification Control Point",
            Characteristic::AlertStatus => "Alert Status",
            Characteristic::Appearance => "Appearance",
            Characteristic::BatteryLevel => "Battery Level",
            Characteristic::BloodPressureFeature => "Blood Pressure Feature",
            Characteristic::BloodPressureMeasurement => "Blood Pressure Measurement",
            Characteristic::BodySensorLocation => "Body Sensor Location",
            Characteristic::BootKeyboardInputReport => "Boot Keyboard Input Report",
            Characteristic::BootMouseInputReport => "Boot Mouse Input Report",
            Characteristic::CSCFeature => "CSC Feature",
            Characteristic::CSCMeasurement => "CSC Measurement",
            Characteristic::CurrentTime => "Current Time",
            Characteristic::CyclingPowerControlPoint => "Cycling Power Control Point",
            Characteristic::CyclingPowerFeature => "Cycling Power Feature",
            Characteristic::CyclingPowerMeasurement => "Cycling Power Measurement",
            Characteristic::CyclingPowerVector => "Cycling Power Vector",
            Characteristic::DateTime => "Data Time",
            Characteristic::DayDateTime => "Day Date Time",
            Characteristic::DayOfWeek => "Day of Week",
            Characteristic::DeviceName => "Device Name",
            Characteristic::DistanceOffset => "Distance Offset",
            Characteristic::ExactTime256 => "Exact Time 256",
            Characteristic::FirmwareRevisionString => "Fireware Revision String",
            Characteristic::GlucoseFeature => "Glucose Feature",
            Characteristic::GlucoseMeasurement => "Glucose Measurement",
            Characteristic::GlucoseMeasurementControl => "Glucose Measurement Control",
            Characteristic::HardwareRevisionString => "Hardware Revision String",
            Characteristic::HeartRateControlPoint => "Heart Rate Control Point",
            Characteristic::HeartRateMeasurement => "Heart Rate Measurement",
            Characteristic::HIDControlPoint => "HID Control Point",
            Characteristic::HIDInformation => "HID Information",
            Characteristic::IEEE1107320601RegulatoryCertificationDataList => "IEEE 1107320601RegulatoryCertificationDataList",
            Characteristic::IntermediateCuffPressure => "Intermediate Cuff Pressure",
            Characteristic:IntermediateTemprature => "Intermediate Temprature",
            Characteristic::LNControlPoint => "LN Control Point",
            Characteristic::LNFeature => "LN Feature",
            Characteristic::LocalTimeInformation => "Local Time Information",
            Characteristic::LocationAndSpeed => "Location and Speed",
            Characteristic::ManufacturerNameString => "Manufacturer Name String",
            Characteristic::MeasurementInterval => "Measurement Interval",
            Characteristic::ModelNumberString => "Model Number String",
            Characteristic::Navigation => "Navigation",
            Characteristic::NewAlert => "New Alert",
            Characteristic::PeripheralPrefferedConnectionParameters => "Peripheral Preffered Connection Parameters",
            Characteristic::PeripheralPrivacyFlag => "Peripheral Privacy Flag",
            Characteristic::PnPID => "PnP ID",
            Characteristic::PositionQuality => "Position Quality",
            Characteristic::ProtocolMode => "Protocol Mode",
            Characteristic::ReconnectionAddress => "Reconnection Address",
            Characteristic::RecordAccessControlPoint => "Record Access Control Point",
            Characteristic::ReferenceTimeInformation => "Reference Time Information",
            Characteristic::Report => "Report",
            Characteristic::ReportMap => "Report Map",
            Characteristic::RingerControlPoint => "Ringer Control Point",
            Characteristic::RingerSetting => "Ringer Setting",
            Characteristic::RSCFeature => "RSC Feature",
            Characteristic::RSCMeasurement => "RSC Measurement",
            Characteristic::SCControlPoint => "SCC Control Point",
            Characteristic::ScanIntervalWindow => "Scan Interval Window",
            Characteristic::ScanRefresh => "Scan Refresh",
            Characteristic::SensorLocation => "Sensor Location",
            Characteristic::SerialNumberString => "Serial Number String",
            Characteristic::ServiceChanged => "Service Changed",
            Characteristic::SoftwareRevisionString => "Software Revision String",
            Characteristic::SupportedNewAlertCategory => "Supported New Alert Category",
            Characteristic::SupportedUnreadAlertCategory => "Supportd Unread Alert Category",
            Characteristic::SystemID => "System ID",
            Characteristic::TemperatureMeasurement => "Temprature Measurement",
            Characteristic::TemperatureType => "Temprature Type",
            Characteristic::TimeAccuracy => "Time Accuracy",
            Characteristic::TimeSource => "Time Source",
            Characteristic::TimeUpdateControlPoint => "Time Update Control Point",
            Characteristic::TimeUpdateState => "Time Update State",
            Characteristic::TimeWithDistance => "Time wit Distance",
            Characteristic::TimeZone => "Timezone",
            Characteristic::TXPowerLevel => "TX Power Level",
            Characteristic::UnreadAlertStatus => "Unread Alert Status",
            Characteristic::AggregateInput => Aggregate Input,
            Characteristic::AnalogInput => "Analog Input",
            Characteristic::AnalogOutput => "Analog Output",
            Characteristic::DigitalInput => "Digital Input",
            Characteristic::DigitalOutput => "Digital Output",
            Characteristic::ExactTime100 => "Exact Time 100",
            Characteristic::NetworkAvailablity => "Network Availability",
            Characteristic::ScientificTemperatureInCelsius => "Scientific Temperature in Celsius",
            Characteristic::SecondaryTimeZone => "Secondary Time Zone",
            Characteristic::String => "String",
            Characteristic::TemperatureInCelsius => "Temperature in Celsius",
            Characteristic::TemperatureInFahrenheit => "Temperature in Fahrenheit",
            Characteristic::TimeBroadcast => "Time Broadcast",
            Characteristic::BatteryLevelState => "Battery Level State",
            Characteristic::BatteryPowerState => "Battery Power State",
            Characteristic::PulseOximetryContinuousMeasurement => "Pulse Oximetry Continuous Measurement",
            Characteristic::PulseOximetrySpotCheckMeasurement => "Pulse Oximetry Spot Check Measurement",
            Characteristic::RecordAccessControlPointTestVersion => "Record Access Control Point Test Version",
            Characteristic::Removable => "Removable",
            Characteristic::ServiceRequired => "Service Required",
            Characteristic::Unknown => "Unknown",
        }
    }
}
